version: '3'

services:

    app:
      build: .
      container_name: app
#      entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
#      entrypoint: dockerize -template ./.docker/nginx/nginx.conf.tmpl:./.docker/nginx/nginx.conf -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
#      environment:
#        - FASTCGI_PASS_NAME=app
#        - FASTCGI_PASS_PORT=9000
      volumes:
        - .:/var/www
      networks: 
        - app-network
      depends_on: 
        - db
        - redis

    nginx:
      build: .docker/nginx
      container_name: nginx
      restart: always
      tty: true
      ports:
        - "8000:80"
      volumes:
        - .:/var/www
      networks: 
        - app-network
      depends_on: 
        - app

    db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true
      ports:
        - "3306:3306"
      environment:
        - MYSQL_DATABASE=laravel
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=root
      networks:
        - app-network
      volumes:
        - ./.docker/dbdata:/var/lib/mysql

    redis:
      image: redis:alpine
      expose:
        - 6379
      networks: 
        - app-network

networks:
  app-network:
    driver: bridge